# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  
- task: Docker@2
  inputs:
    containerRegistry: 'MyDemoACR'
    command: 'login'
    
- task: DotNetCoreCLI@2
  displayName: 'Basic Publish TestAPI'
  inputs:
    projects: 'TestAPI/TestAPI.csproj'
    command: 'publish'
    publishWebProjects: false
    arguments: '-p ContainerRegistry=myblogcontainerizedemo.azurecr.io'
    zipAfterPublish: false



- task: DotNetCoreCLI@2
  displayName: 'Build DemoAppsWithPrivateNugetFeed'
  inputs:
    command: 'build'
    projects: 'DemoAppWithPrivateNugetFeed/DemoAppWithPrivateNugetFeed.csproj'
    feedsToUse: 'select'
    vstsFeed: '2c2e3cab-e1e3-45e4-aa52-0331175b406e/LocalPackagesDemo'


- task: DotNetCoreCLI@2
  displayName: 'test Publish DemoAppsWithPrivateNugetFeed'
  inputs:
    command: 'publish'
    projects: 'DemoAppWithPrivateNugetFeed/DemoAppWithPrivateNugetFeed.csproj'
    publishWebProjects: false
    ZipAfterPublish: false
    feedsToUse: 'select'
    vstsFeed: '2c2e3cab-e1e3-45e4-aa52-0331175b406e/LocalPackagesDemo'



- task: DotNetCoreCLI@2
  displayName: 'Basic Publish DemoAppsWithPrivateNugetFeed'
  inputs:
    command: 'publish'
    projects: 'DemoAppWithPrivateNugetFeed/DemoAppWithPrivateNugetFeed.csproj'
    publishWebProjects: false
    ZipAfterPublish: false
    arguments: '/t:PublishContainer -p ContainerRegistry=myblogcontainerizedemo.azurecr.io'
    feedsToUse: 'select'
    vstsFeed: '2c2e3cab-e1e3-45e4-aa52-0331175b406e/LocalPackagesDemo'
