# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  
- task: Docker@2
  inputs:
    containerRegistry: 'MyDemoACR'
    command: 'login'
    
- task: DotNetCoreCLI@2
  inputs:
    projects: 'TestAPI\TestAPI.csproj'
    command: 'publish'
    publishWebProjects: true
    arguments: '-p ContainerRegistry=myblogcontainerizedemo.azurecr.io'
    zipAfterPublish: false

- task: DotNetCoreCLI@2
  inputs:
    projects: 'DemoAppWithPrivateNugetFeed\DemoAppWithPrivateNugetFeed.csproj'
    command: 'publish'
    publishWebProjects: true
    arguments: '-p ContainerRegistry=myblogcontainerizedemo.azurecr.io'
    zipAfterPublish: false    