trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  nugetPackageVersion: '1.0.0'

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: 'HelloWorld/HelloWorld.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'HelloWorld/HelloWorld.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: 'HelloWorld/HelloWorld.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'nugetPackageVersion'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish NuGet package'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nuget-package'
    publishLocation: 'Container'
    targetPath: '$(Build.ArtifactStagingDirectory)/$(ArtifactName)'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet package locally'
  inputs:
    command: 'custom'
    custom: 'nuget push --source "https://pkgs.dev.azure.com/LaurentAerens/2c2e3cab-e1e3-45e4-aa52-0331175b406e/_packaging/LocalPackagesDemo/nuget/v3/index.json" --api-key az $(Build.ArtifactStagingDirectory)/nuget-package/HelloWorld.1.0.0.nupkg'