# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  
- task: Docker@2
  inputs:
    containerRegistry: 'MyDemoACR'
    command: 'login'
    
- task: DotNetCoreCLI@2
  displayName: 'Basic Publish TestAPI'
  inputs:
    projects: 'TestAPI/TestAPI.csproj'
    command: 'publish'
    publishWebProjects: false
    arguments: '-p ContainerRegistry=myblogcontainerizedemo.azurecr.io'
    zipAfterPublish: false


- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: 'DemoAppWithPrivateNugetFeed/DemoAppWithPrivateNugetFeed.csproj'
    feedsToUse: 'config'
    nugetConfigPath: 'DemoAppWithPrivateNugetFeed/nuget.config'

- task: DotNetCoreCLI@2
  displayName: 'Basic Publish DemoAppsWithPrivateNugetFeed'
  inputs:
    command: 'publish'
    projects: 'DemoAppWithPrivateNugetFeed/DemoAppWithPrivateNugetFeed.csproj'
    publishWebProjects: false
    ZipAfterPublish: false
    arguments: '/t:PublishContainer -p ContainerRegistry=myblogcontainerizedemo.azurecr.io'


- task: DotNetCoreCLI@2
  displayName: 'Advanced Publish TestAPI'
  inputs:
    projects: 'TestAPI/TestAPI.csproj'
    command: 'publish'
    publishWebProjects: false
    arguments: '-p ContainerRegistry=myblogcontainerizedemo.azurecr.io -p ContainerRepository=testapiAlpine -p ContainerFamily=alpine -p ContainerRuntimeIdentifier=linux-x64 -p ContainerImageTags=\'"1.0.0;latest"\' -p ContainerUser=root'
    zipAfterPublish: false